### ISSUE TITLE
USER STORY : View Task List

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#1]
As **User** i can **view the task list** so that i can **select and check the task i need to do**

**Acceptance Criteria**

- [x] The user can access the task list page.
- [x] The task list displays all tasks with their titles.
- [x] The user can see an indication of completed tasks.

**Task**

- [x] Design the task list page UI.
- [x] Fetch the list of tasks from the backend.
- [x] Render the tasks on the task list page
- [x] Implement the indication of completed tasks.
- [x] Test and verify that the task list is displayed correctly.
