### ISSUE TITLE
USER STORY : Manage tasks

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#3]
As **User ** i can **read, add, update and delete tasks** so that i can **manage my tasks list**

**Acceptance Criteria**

- [x] The user can create new tasks.
- [x] The user can edit existing tasks.
- [x] The user can delete tasks.

**Tasks**

- [x] Design the UI for creating, editing, and deleting tasks.
- [x] Implement the functionality to create new tasks.
- [x] Implement the functionality to edit existing tasks.
- [x] Implement the functionality to delete tasks.
- [x] Test and verify the task management functions.
