### ISSUE TITLE
USER STORY : Mark a task as completed

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#4]
As **User** i can **mark a completed checkbox and strike a task off** so that i  **know which tasks dont have to be done**

**Acceptance Criteria**

- [x] The user can mark a task as completed.
- [x] Completed tasks are visually distinguished from active tasks.

**Tasks**

- [x] Add a checkbox or button to mark tasks as completed.
- [x] Implement the functionality to toggle the completion status of tasks.
- [x] Update the visual representation of completed tasks.
- [x] Test and verify marking tasks as completed.
