### ISSUE TITLE
USER STORY : Search a task

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#5]
As **User** i can **search for a particular task** so that i can **be quicker in finding the task i'm interested into**

**Acceptance Criteria**

- [x] The user can search for a task by its title.
- [x] Search results display matching tasks.

**Tasks**

- [x] Design the search functionality UI.
- [x] Implement the search functionality to filter tasks by title.
- [x] Update the task list display based on the search results.
- [x] Test and verify the search functionality.
