### ISSUE TITLE
USER STORY : Important task

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#6]
As **User** i can **mark a task as important** so that i can **know which tasks i need to prioritize**

**Acceptance Criteria:**

- [ ]  The user can mark a task as important.
- [ ]  Important tasks are visually distinguished from other tasks.
- [ ]  The user can remove the importance status from a task.

**Tasks:**

- [ ] Design the UI to indicate the importance status of a task.
- [ ] Implement the functionality to mark a task as important.
- [ ] Update the visual representation of important tasks to visually distinguish them.
- [ ] Implement the functionality to remove the importance status from a task.
- [ ] Test and verify marking tasks as important and removing the importance status.
- [ ]
