### ISSUE TITLE
USER STORY : Account registration

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#7]
As **User** i can **register a new account** so that i can **be the only person that has access to the tasks list**

**Acceptance Criteria**

- [x] The user can register a new account.
- [x] Account registration ensures unique access to the task list.

**Tasks**

- [x] Design the account registration UI.
- [x] Implement the registration form with appropriate fields (e.g., username, password).
- [x] Implement backend logic to handle account registration and restrict access only to the looged in user .
- [x] Test and verify the account registration process.
