### ISSUE TITLE
USER STORY :Set Task Due Date and Receive Reminders

### ISSUE THREAD

**Issue by Villelligiulia** [Villelligiulia/No-Excuses#8]
As **User** i can **set a due date and receive reminders** so that **I won't forget to do any task**

**Acceptance Criteria**:

- [ ] The user can set a due date for a task.
- [ ] The user receives reminders for upcoming tasks.

**Tasks**:

- [ ] Design the UI for setting a due date for tasks.
- [ ] Implement the functionality to set a due date for tasks.
- [ ] Integrate a reminder system to send notifications for upcoming tasks.
- [ ] Test and verify the ability to set task due dates and receive reminders.
